In [1]:
from maincode1 import scrapper
from maincode2 import runn

In [2]:
bound1 = 192730
bound2 = 192738
bound3 = 0
bound4 = 0
bound5 = 189642
bound6 = bound5
paralell = 1


df1 = scrapper(bound1,bound2,bound3,bound4)
df2 = scrapper(bound5,bound5+1,bound5,bound5)

ID: 192730 start
ID: 192730 done

ID: 192731 start
ID: 192731 done

ID: 192732 start
ID: 192732 done

ID: 192733 start
ID: 192733 done

ID: 192734 start
ID: 192734 done

ID: 192735 start
ID: 192735 done

ID: 192736 start
ID: 192736 done

ID: 192737 start
ID: 192737 done

ID: 189642 start
ID: 189642 done

In [3]:
df1

,matkul,jenis,paralel,hari,jam,ruangan,JadwalID
0,Fisika Kuantum,K,2,Senin,15:00-16:40,RK. X.303,313211
1,Fisika Kuantum,K,1,Selasa,15:00-16:40,RK. X.303,313210
2,Fisika Kuantum,R,2,Rabu,07:00-08:40,RK. 16 FAC 401 C,313213
3,Fisika Kuantum,R,1,Kamis,15:30-17:10,RK. 16 FAC 401 D,313212
4,Fisika Statistik,K,1,Senin,08:00-09:40,RK. Teaching LAB TPB.2.3,313214
5,Fisika Statistik,K,2,Selasa,13:00-14:40,RK. OFAC 4 B12,313215
6,Fisika Statistik,R,1,Rabu,13:00-14:40,RK. Teaching LAB TPB.2.3,313216
7,Fisika Statistik,R,2,Jumat,15:30-17:10,RK. 16 FAC 401 B,313217
8,Fisika Sistem Kompleks,K,1,Selasa,10:00-11:40,RK. Teaching LAB TPB.2.4,313218
9,Fisika Sistem Kompleks,K,2,Kamis,10:00-11:40,RK. X.304,313219
10,Optika dan Fotonika,K,2,Rabu,15:00-16:40,RK. X.301,313221
11,Optika dan Fotonika,K,1,Kamis,13:00-14:40,RK. X.304,313220
12,Metode Karakterisasi Material,K,1,Senin,13:00-13:50,RK. 16 FAC 401 D,313222
13,Metode Karakterisasi Material,K,2,Selasa,10:00-10:50,RK. Teaching LAB TPB.2.3,313223
14,Metode Karakterisasi Material,P,2,Kamis,13:00-15:00,RK. 15 TAN 301 B,313225
15,Metode Karakterisasi Material,P,1,Jumat,09:30-11:30,RK. OFAC 4 B12,313224
16,Sistem Instrumentasi berbasis Internet,K,2,Selasa,08:00-08:50,RK. 16 FAC 401 D,313227
17,Sistem Instrumentasi berbasis Internet,K,1,Kamis,10:00-10:50,RK. 16 FAC 401 B,313226
18,Sistem Instrumentasi berbasis Internet,P,2,Jumat,07:00-09:00,Ruangan Disesuaikan,313229
19,Sistem Instrumentasi berbasis Internet,P,1,Jumat,13:30-15:30,Ruangan Disesuaikan,313228
20,Sensor dan Transduser,K,2,Senin,10:00-10:50,RK. Teaching LAB TPB.2.4,313231
21,Sensor dan Transduser,K,1,Selasa,08:00-08:50,RK. X.302,313230
22,Sensor dan Transduser,P,1,Rabu,15:00-17:00,Ruangan Disesuaikan,313232
23,Sensor dan Transduser,P,2,Kamis,15:00-17:00,Ruangan Disesuaikan,313233
24,Biomaterial,K,2,Rabu,13:00-14:40,RK. X.303,313235
25,Biomaterial,K,1,Kamis,08:00-09:40,RK. OFAC 4 B11,313234

In [4]:
df1 = df1[df1['paralel']=='1']
df1 = df1[['matkul','hari','jam','paralel']]
df2 = df2[['matkul','hari','jam','paralel']]

display(df1)

                                    matkul    hari           jam paralel
1                           Fisika Kuantum  Selasa  15:00-16:40        1
3                           Fisika Kuantum   Kamis  15:30-17:10        1
4                         Fisika Statistik   Senin  08:00-09:40        1
6                         Fisika Statistik    Rabu  13:00-14:40        1
8                   Fisika Sistem Kompleks  Selasa  10:00-11:40        1
11                     Optika dan Fotonika   Kamis  13:00-14:40        1
12           Metode Karakterisasi Material   Senin  13:00-13:50        1
15           Metode Karakterisasi Material   Jumat  09:30-11:30        1
17  Sistem Instrumentasi berbasis Internet   Kamis  10:00-10:50        1
19  Sistem Instrumentasi berbasis Internet   Jumat  13:30-15:30        1
21                   Sensor dan Transduser  Selasa  08:00-08:50        1
22                   Sensor dan Transduser    Rabu  15:00-17:00        1
25                             Biomaterial   Kamis  08:00-09:40        1

In [5]:
df1[['mulai','selesai']] = df1['jam'].str.split("-",n=1,expand=True)
df2[['mulai','selesai']] = df2['jam'].str.split("-",n=1,expand=True)
df1['startMin'] = df1['mulai'].str[0:2].astype(int)*60 + df1['mulai'].str[3:5].astype(int)
df2['startMin'] = df2['mulai'].str[0:2].astype(int)*60 + df2['mulai'].str[3:5].astype(int)
df1['endMin'] = df1['selesai'].str[0:2].astype(int)*60 + df1['selesai'].str[3:5].astype(int)
df2['endMin'] = df2['selesai'].str[0:2].astype(int)*60 + df2['selesai'].str[3:5].astype(int)

In [6]:
def check_overlap(row, df_ref):
    for _, ref in df_ref.iterrows():
        if row["startMin"] < ref["endMin"] and row["endMin"] > ref["startMin"]:
            return True

    return False

In [7]:
grouped1 = df1.groupby(by='hari')
overlap_hasil = []
for _,row in df2.iterrows():
    hari = row['hari']

    if hari in grouped1.groups:
        overlap = check_overlap(
            row,
            grouped1.get_group(hari)
        )
    else:
        overlap = False
    
    overlap_hasil.append(overlap)
df2['overlap'] = overlap_hasil

df2["overlaps"] = df2.apply(
lambda row: (
    check_overlap(row, grouped1.get_group(row["hari"]))
    if row["hari"] in grouped1.groups
    else False
),
axis=1
)
df2New = df2[df2['overlap']==False]

In [10]:
df2["overlap"] = df2["overlap"].apply(
    lambda x: "✅" if x else "❌"
)
display(df2)

,matkul,hari,jam,paralel,mulai,selesai,startMin,endMin,overlap,overlaps
0,Metode Statistika,Selasa,08:00-09:40,11,08:00,09:40,480,580,✅,True
1,Metode Statistika,Selasa,10:00-11:40,15,10:00,11:40,600,700,✅,True
2,Metode Statistika,Rabu,08:00-09:40,1,08:00,09:40,480,580,✅,False
3,Metode Statistika,Rabu,10:00-11:40,8,10:00,11:40,600,700,✅,False
4,Metode Statistika,Rabu,10:00-11:40,9,10:00,11:40,600,700,✅,False
5,Metode Statistika,Rabu,11:15-13:15,7,11:15,13:15,675,795,✅,True
6,Metode Statistika,Rabu,11:15-13:15,5,11:15,13:15,675,795,✅,True
7,Metode Statistika,Rabu,14:00-16:30,6,14:00,16:30,840,990,✅,True
8,Metode Statistika,Rabu,14:00-16:30,3,14:00,16:30,840,990,✅,True
9,Metode Statistika,Kamis,08:00-09:40,2,08:00,09:40,480,580,✅,True
10,Metode Statistika,Kamis,08:00-10:00,15,08:00,10:00,480,600,✅,True
11,Metode Statistika,Kamis,10:00-11:40,14,10:00,11:40,600,700,✅,True
12,Metode Statistika,Kamis,13:00-14:40,10,13:00,14:40,780,880,✅,True
13,Metode Statistika,Kamis,13:00-15:00,14,13:00,15:00,780,900,✅,True
14,Metode Statistika,Kamis,13:00-15:00,2,13:00,15:00,780,900,✅,True
15,Metode Statistika,Jumat,07:00-09:00,10,07:00,09:00,420,540,✅,False
16,Metode Statistika,Jumat,07:00-09:00,11,07:00,09:00,420,540,✅,False
17,Metode Statistika,Jumat,09:00-10:40,12,09:00,10:40,540,640,✅,True
18,Metode Statistika,Jumat,09:00-10:40,13,09:00,10:40,540,640,✅,True
19,Metode Statistika,Jumat,09:30-11:30,4,09:30,11:30,570,690,✅,True
20,Metode Statistika,Jumat,10:00-12:00,1,10:00,12:00,600,720,✅,True
21,Metode Statistika,Jumat,13:30-15:10,3,13:30,15:10,810,910,✅,True
22,Metode Statistika,Jumat,13:30-15:10,5,13:30,15:10,810,910,✅,True
23,Metode Statistika,Jumat,13:30-15:10,4,13:30,15:10,810,910,✅,True
24,Metode Statistika,Jumat,13:30-15:10,7,13:30,15:10,810,910,✅,True
25,Metode Statistika,Jumat,13:30-15:10,6,13:30,15:10,810,910,✅,True
26,Metode Statistika,Jumat,13:30-15:10,8,13:30,15:10,810,910,✅,True
27,Metode Statistika,Jumat,13:30-15:10,9,13:30,15:10,810,910,✅,True
28,Metode Statistika,Jumat,13:30-15:30,13,13:30,15:30,810,930,✅,True
29,Metode Statistika,Jumat,13:30-15:30,12,13:30,15:30,810,930,✅,True